### PR TITLE
Feat/remove acrosssegorseggroup

### PR DESCRIPTION
**Pull request by sanjayankur31**
Fixes https://github.com/NeuroML/NeuroML2/issues/162

Need to test it with jneuroml etc. now.

### CODE REVIEW

**Comment by sanjayankur31** [comment]
jneuroml builds fine, libNeuroML passes all tests with the regenerated nml.py file also:

https://github.com/NeuralEnsemble/libNeuroML/pull/104/checks?check_run_id=2897167645

@pgleeson : what more should one test to make sure this is OK?

**Comment by pgleeson** [comment]
@sanjayankur31 Why are the value attributes on InitMembPotential etc. optional? Surely they are the one thing that should be required?

**Comment by sanjayankur31** [comment]
Hrm, they were optional in the `ValueAcrossSegOrSegGroup` class that these were extending, so I set them optional again here. Should I update them to be necessary?

**Comment by pgleeson** [comment]
Yep, that was a way too lenient base class... Make all the values required...

**Comment by sanjayankur31** [comment]
Great, doing that now and regenerating nml.py again

**Comment by sanjayankur31** [comment]
Also: should `species` also have a `value` attribute? it isn't listed here in the schema: https://docs.neuroml.org/Userdocs/Schemas/Cells.html#species

**Comment by pgleeson** [comment]
> Also: should `species` also have a `value` attribute? it isn't listed here in the LEMS defs: https://docs.neuroml.org/Userdocs/Schemas/Cells.html#species

No, see e.g.: https://github.com/NeuroML/NeuroML2/blob/master/LEMSexamples/LEMS_NML2_Ex15_CaDynamics.xml#L316

**Pull request merged**
