### PR TITLE
feat(schema): add simple type to restrict component reference paths

### PR DESCRIPTION
**Pull request by sanjayankur31**
The regex says that the path must be a string that:

- may start with a `/`
- followed by any number of the following strings optionally suffixed with a `/`
  - `../`
  - `./`
  - `[0-9]`
  - a string with the first letter as an alphanumberic letter, followed by any number of alphanumeric + `_` letters

### CODE REVIEW

**Comment by sanjayankur31** [comment]
To test with `xmllint`, something like this will do (replace path of xsd here):

```
find . -name "*.nml" -execdir xmllint --schema /home/asinha/Documents/02_Code/00_mine/NeuroML/software/NeuroML2/Schemas/NeuroML2/NeuroML_v2.3.xsd --noout '{}' \; 2> validation-output.txt
```

Question: can the `[]` be empty or non numeric?

**Comment by pgleeson** [comment]
@sanjayankur31 See https://github.com/NeuroML/org.neuroml.export/blob/development/src/main/java/org/neuroml/export/utils/Utils.java#L127

I think all paths in projection/connections and inputList/inputs will be of the form
../pop_pyr/0/pyr_4_sym
or
../pop_pyr[0]

and all in explicit inputs will be 

pop_pyr/0/pyr_4_sym
or
pop_pyr[0]

I would limit it to only these options until you find any other examples. Test on all in https://github.com/NeuroML/NeuroML2/tree/master/examples

**Comment by sanjayankur31** [comment]
@pgleeson : limited to the possible paths now. All examples validate, and tested a bunch of models too.

**Comment by pgleeson** [comment]
Thanks, testing on exp

**Comment by pgleeson** [comment]
Looks good. The extra java based tests in jnml are actually quite informative too, e.g. if you put the wrong population id in the string of connection and it doesn't match the one in projection.

**Comment by sanjayankur31** [comment]
> Looks good. The extra java based tests in jnml are actually quite informative too, e.g. if you put the wrong population id in the string of connection and it doesn't match the one in projection.

Cool. I'd gone through the various bits and listed them out in the docs here (and also in the appendix of the paper):

https://docs.neuroml.org/Userdocs/ValidatingNeuroMLModels.html#list-of-validation-tests

**Pull request merged**
